### ISSUE TITLE
Ch04 Virtual Process Memory_p329

### ISSUE THREAD

**Issue by SonJuHyung** [DKU-Embedded-Lab/Professional-Linux-Kernel-Architecture#2]
스터디 자료 : [Professional Linux Kernel Architecture](http://cse.yeditepe.edu.tr/~kserdaroglu/spring2014/cse331/termproject/BOOKS/ProfessionalLinuxKernelArchitecture-WolfgangMauerer.pdf)
  시간 : 11/20 PM 8:30 분(매주)
  장소 : 미디어센터 508 호

# 발표팀
## 1. Ch04 스터디 및 커널 분석 자료 작성 
전체 적인 그림 및 구조 설명
일정 
- 11 월 20 일 발표 - 4.9 ( p290 ~ p329 ) 까지

###     -  include/linux
       mm_types.h, mm.h, fs.h, fremap.c, rmap.c
###     -  arch/x86/mm
       mmap_32.c,  mmap.c, extable_32.c
###     -  mm
        mmap.c, filemap.c, nommu.c, memory.c
###    -  include/asm-ia64
        pgtable.h
###    -  arch/x86/mm
        fault_32.c, fault.c

# 발표팀 이외 팀
## 1. Ch04 에 대하여 팀당 질문 총 6개(개인 당 3개)를 만들어 하루전까지 해당 issue 에 comment 로 제출\
- 11월 19일까지 issue 에 질문 comment  작성
## 2. Ch02 11/13 발표팀 질문사항에 대한 설명.

**Comment by heyheygo99** [comment]
질문 1.

- [x] However, 64-bit architectures are often binary-compatible with their predecessors. If a 32-bit binary is executed on a 64-bit machine, then task_size describes the effective task size visible to the binary.(291페이지): 32비트 바이너리가 64비트 시스템에서 실행되는 경우엔 task_size가 유효 크기를 나타낸다고 했는데, 위에 문장에서 64비트 아키텍쳐에서 종종 binary-compatible 하다는 말이 어떤 얘기인가요?

질문 2.
- [x] Using the described address space layout works very well on machines that provide a large virtual address space. However, problems can arise on 32-bit machines. (293페이지): 32비트 시스템에서는 IA-32 상황일 땐, 어떤 방식으로 가상 주소 공간을 나누나요?(IA-32 상황은 또 어떤건가요?)

질문 3. 
- [x] This is usually the case, but is disabled for Transmeta CPUs because it has a negative speed impact on such machines. (294페이지): Transmeta CPU가 어떤건가요?

**Comment by SonJuHyung** [comment]
## @heyheygo99 질문 사항
### 질문 1. 32 bit ELF on 64 bit
TASK_SIZE 는 x86 의 경우 [arch/x86/include/asm/processor.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/processor.h#L800) 위치에 32bit 의 경우 아래와 같이 정의되어 있습니다.  
```c
#define   CONFIG_X86_32
// 32 bit 의 경우
#define   TASK_SIZE   PAGE_OFFSET
#define   TASK_SIZE_MAX   TASK_SIZE
//...
#else
// 64 bit 의 경우
#define   TASK_SIZE_MAX   ((1UL << 47) - PAGE_SIZE)                                                                                                                                                             
#define   IA32_PAGE_OFFSET   ((current->personality & ADDR_LIMIT_3GB) ? 0xc0000000 : 0xFFFFe000)                                                  
#define   TASK_SIZE   (test_thread_flag(TIF_ADDR32) ? IA32_PAGE_OFFSET : TASK_SIZE_MAX)
```

- 32 bit 의 경우 [arch/x86/include/asm/page_types.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/page_types.h#L35) 위치에 PAGE_OFFSET 이 __PAGE_OFFSET 으로 정의되어 있으며
```c
#define   PAGE_OFFSET   ((unsigned long)__PAGE_OFFSET)
```
__PAGE_OFFSET 은 [arch/x86/include/asm/page_32_types.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/page_32_types.h#L17) 위치에 아래와 같이 정의되어 있습니다. 
CONFIG_PAGE_OFFSET 은 kernel build time 에 3G 로 정해지며  .config 파일을 통해 조정 할 수 있습니다.
```c
#define   __PAGE_OFFSET_BASE	_AC(CONFIG_PAGE_OFFSET, UL)
#define   __PAGE_OFFSET		__PAGE_OFFSET_BASE
```
- 64 bit 경우 [include/linux/thread_info.h](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/thread_info.h#L74) 에 보시면 current_thread_info 를 통해 가져올 수 있는 [struct thread_info](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/thread_info.h#L55) 의 flags 를 검사하여 [test_ti_thread_flag](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/thread_info.h#L61) 함수를 통해 [TIF_ADDR32](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/thread_info.h#L100) flag 를 검사합니다. TIF_ADDR32 flags 는 x86 specific 한 flag 로 32-bit address space 로 설정되었음을 나타내는 flag 입니다.
```c
#define TASK_SIZE	(test_thread_flag(TIF_ADDR32) ? IA32_PAGE_OFFSET : TASK_SIZE_MAX)
```
설정되어 있다면 [IA32_PAGE_OFFSET](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/processor.h#L846) 이 설정되어 있는지 한번 더 검사 합니다. IA32_PAGE_OFFSET 는 64 bit 에서 32-bit ELF 를 위해 personality system call 로 address space 크기를 조정하는 x86 specific flag 입니다.  설정된 경우 결과적으로 해당 프로세스의 task_strut->task_size 에 초기화될 TASK_SIZE 가 3GB가 됩니다. 
```c
#define IA32_PAGE_OFFSET	((current->personality & ADDR_LIMIT_3GB) ? 0xc0000000 : 0xFFFFe000)
```
TIF_ADDR32 가 설정되어 있지 않다면 [arch/x86/include/asm/processor.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/processor.h#L841) 에 서 볼 수 있는 것 처럼 guard page 1 개 4KB 만큼을 제외하고 128TB 크기의 address space 를 가지게 됩니다. 
```c
#define TASK_SIZE_MAX	((1UL << 47) - PAGE_SIZE)
```

### 질문 2. IA-32 address space layout
p292 에 나와있는 Figure 4-1 을 보시기 바랍니다. 
### 질문 3.
작성중

**Comment by sungmin1989** [comment]
- [x] 질문 1.
이번장에 어울리는 질문인지 모르겠습니다.(손주형 이 이번 챕터를 맡았기 때문에 질문함) 구체적인 내용보다 전체적인 그림을 한번 보고 싶습니다. secondary storage에서 메모리로 load되고 (아마 demand page 기법을 사용하겠죠) cpu로 올라가고 캐시에 집어넣고 etc... 이 전체적인 data 흐름을 먼저 그려 주시면 내용 이해가 한결 편할 것 같습니다. 

- [ ] 질문 2.
 MMU를 S/W로 구성하지 않고 H/W로 구성해야하는 이유와 장점은 무엇인가요?

- [x] 질문 3.
초기에 반드시 메모리로 올려야하는 것들은 어떤 것들이 있나요?

- [ ] 질문 4.
가상 메모리가 부족할 수 있는 경우가 발생할 수 있나요? 이 경우에는 어떻게 커널에서 처리를 하나요?

**Comment by kwanghee0124** [comment]
- [x] 질문 1.
현재 책에서 사용한 커널이 2.6.x 대 버전으로 설명하고 있고 지금 주로 사용되는 커널은 4.x.x 대 버전의 커널을 사용하는데 메모리 구조 관리를 할때 red-black tree를 사용하게 되는데
4.x.x 커널 버전에서 레드 블랙 트리 말고 메모리 관리 할때 추가 하여 사용하는 트리가 있는지 아니면 레드 블랙 트리가 쭉 사용되어 왔다면 업데이트 되어 있는 부분이 있는지 궁금합니다.

- [x] 질문 2.
(p.304) 그림 4-8를 보여주면서 겹치는 간격에 관한 얘기가 나오는데 B,C,D가 A에 완전히 속하면 A는 부모 요소가 되는데 만약에 완전히 겹치지 않고 4-8처럼 일부분만 겹치게 되면 어떤식으로 관리하게 되나요. 그위에 간격 간에 고유의 색인을 가지고 있어서 괜찮다고는 하는데 이 부분에 대한 설명이 너무 부족한거 같아서 질문 올립니다.

- [x] 질문 3.
(p.324) 부분에서 Reverse Mapping을 설명하는 부분이 있는데 여기서 익명 페이지(Anonymous Pages)가 어떤 페이지를 나타내는건지 잘 모르겠습니다.

**Comment by bestjae** [comment]
- [ ] 질문 1.
메모리 메핑에 사용되는 mmap, mmap2 시스템 콜이 사용가능한 주소공간보다큰 경우에 사용한다고 되어있는데 어떤원리로 그게 가능한지 잘 이해가 안됩니다.

- [x] 질문 2.
mm_type.h
struct mm_struct{
	struct vm_area_struct * mmap; 
	struct rb_root mm_rb; 	struct vm_area_struct * mmap_cache; 
	... 
}
mmap_cache 의 역할과 mmap_cache 가 없어도 되는지 궁금합니다.

- [x] 질문 3.
312p
It provides an operation to read pages not yet in physical memory although their contents have already been mapped there.
실제 메모리에는 없지만 이미 매핑 되어있는 페이지에 대한 읽기지원? 이 어떤 의미인지 잘 모르겠습니다.
메모리는 없는데 읽기가 가능한가요?

**Comment by MyunghoonOh** [comment]
- [x] 질문 1.
프로세스의 Virtual Adress Space에서 Stack과 MMAP영역이 충돌한다면, 어떻게 처리를 하는지 궁금합니다.

- [x] 질문 2.
Page table에서 Nonlinear mapping 엔트리를 표현하는 방법과 
sys_remap_file_pages 함수를 보여주는 319 Page에서 "The system call allows for rearranging pages in a mapping such that the order in memory is not identical with the order in the file. This is achieved without moving the memory contents around, but is instead performed by manipulating the page tables of the process"가 이해가 안됩니다.

- [x] 질문 3.
Reverse Mapping 부분에서 Anonymous Pages와 Pages with a File-Based Mapping의 차이점이 궁금합니다.

**Comment by SonJuHyung** [comment]
## @heyheygo99 질문 사항
### 질문 1. 32 bit ELF on 64 bit 실행 결과는?(binary-compatible)
TASK_SIZE 는 x86 의 경우 [arch/x86/include/asm/processor.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/processor.h#L800) 위치에 32bit 의 경우 아래와 같이 정의되어 있습니다.  
```c
#define   CONFIG_X86_32
// 32 bit 의 경우
#define   TASK_SIZE   PAGE_OFFSET
#define   TASK_SIZE_MAX   TASK_SIZE
//...
#else
// 64 bit 의 경우
#define   TASK_SIZE_MAX   ((1UL << 47) - PAGE_SIZE)                                                                                                                                                             
#define   IA32_PAGE_OFFSET   ((current->personality & ADDR_LIMIT_3GB) ? 0xc0000000 : 0xFFFFe000)                                                  
#define   TASK_SIZE   (test_thread_flag(TIF_ADDR32) ? IA32_PAGE_OFFSET : TASK_SIZE_MAX)
```

- 32 bit 의 경우 [arch/x86/include/asm/page_types.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/page_types.h#L35) 위치에 PAGE_OFFSET 이 __PAGE_OFFSET 으로 정의되어 있으며
```c
#define   PAGE_OFFSET   ((unsigned long)__PAGE_OFFSET)
```
__PAGE_OFFSET 은 [arch/x86/include/asm/page_32_types.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/page_32_types.h#L17) 위치에 아래와 같이 정의되어 있습니다. 
CONFIG_PAGE_OFFSET 은 kernel build time 에 3G 로 정해지며  .config 파일을 통해 조정 할 수 있습니다.
```c
#define   __PAGE_OFFSET_BASE	_AC(CONFIG_PAGE_OFFSET, UL)
#define   __PAGE_OFFSET		__PAGE_OFFSET_BASE
```
- 64 bit 경우 [include/linux/thread_info.h](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/thread_info.h#L74) 에 보시면 current_thread_info 를 통해 가져올 수 있는 [struct thread_info](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/thread_info.h#L55) 의 flags 를 검사하여 [test_ti_thread_flag](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/thread_info.h#L61) 함수를 통해 [TIF_ADDR32](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/thread_info.h#L100) flag 를 검사합니다. TIF_ADDR32 flags 는 x86 specific 한 flag 로 32-bit address space 로 설정되었음을 나타내는 flag 입니다.
```c
#define TASK_SIZE	(test_thread_flag(TIF_ADDR32) ? IA32_PAGE_OFFSET : TASK_SIZE_MAX)
```
설정되어 있다면 [IA32_PAGE_OFFSET](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/processor.h#L846) 이 설정되어 있는지 한번 더 검사 합니다. IA32_PAGE_OFFSET 는 64 bit 에서 32-bit ELF 를 위해 personality system call 로 address space 크기를 조정하는 x86 specific flag 입니다.  설정된 경우 결과적으로 해당 프로세스의 task_strut->task_size 에 초기화될 TASK_SIZE 가 3GB가 됩니다. 
```c
#define IA32_PAGE_OFFSET	((current->personality & ADDR_LIMIT_3GB) ? 0xc0000000 : 0xFFFFe000)
```
TIF_ADDR32 가 설정되어 있지 않다면 [arch/x86/include/asm/processor.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/processor.h#L841) 에 서 볼 수 있는 것 처럼 guard page 1 개 4KB 만큼을 제외하고 128TB 크기의 address space 를 가지게 됩니다. 
```c
#define TASK_SIZE_MAX	((1UL << 47) - PAGE_SIZE)
```

### 질문 2. IA-32 address space layout 은 ?
p292 에 나와있는 Figure 4-1 을 보시기 바랍니다. 
### 질문 3.
작성중

## @sungmin1989  질문 사항
### 질문 1. 그림
내용
### 질문 2. MMU 가 S/W 가아닌 H/W 로 구성되어야 하는 이유는?
내용
### 질문 3. ELF binary loading 시 반드시 memory 로 올려야 하는 것들은?
내용

## @kwanghee0124 질문 사항
### 질문 1. virtual processor address 관리 rbtree 및 update 사항은?
내용
### 질문 2. Priority Search Tree(PST) 에서 interval 겹치면 어떻게되나?
내용
### 질문 3. Anonymous Page 란?
내용

## @bestjae  질문 사항
### 질문 1. ?
내용
### 질문 2. mmap_cache 의 역할은?
내용
### 질문 3. 해석
내용

## @MyunghoonOh   질문 사항
### 질문 1. legacy layout 에서 stack 과  mmap 이 충돌한다면 어떻게 되는가?
내용
### 질문 2. sys_remap_file_pages
내용
### 질문 3. anonymous page 와 file-backed page 의 차이는?
내용

**Comment by irian38317** [comment]
- [x] 질문 1.
p290
 The kernel must therefore concentrate on managing user address spaces as efficiently as possible by resorting to a few tricks.
 질문 : 저 몇 가지 트릭이 어떤 것들이 있습니까?

- [x] 질문 2.
Virtual Address Space에서 Heap과 MMAP영역이 충돌시, 어떻게 해결합니까?

- [x] 질문 3.
p312
It provides an operation to read pages not yet in physical memory although their contents have already been mapped there.
메모리에 없는 걸 어떻게 읽는 건지 잘 모르겠습니다.

**Comment by SonJuHyung** [comment]
# 11/20 스터디 질문 답변
-----------------------------
## @heyheygo99 질문 사항
### 질문 1. 32 bit ELF on 64 bit 실행 결과는?(binary-compatible)
TASK_SIZE 는 x86 의 경우 [arch/x86/include/asm/processor.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/processor.h#L800) 위치에 32bit 의 경우 아래와 같이 정의되어 있습니다.  
```c
#define   CONFIG_X86_32
// 32 bit 의 경우
#define   TASK_SIZE   PAGE_OFFSET
#define   TASK_SIZE_MAX   TASK_SIZE
//...
#else
// 64 bit 의 경우
#define   TASK_SIZE_MAX   ((1UL << 47) - PAGE_SIZE)                                                                                                                                                             
#define   IA32_PAGE_OFFSET   ((current->personality & ADDR_LIMIT_3GB) ? 0xc0000000 : 0xFFFFe000)                                                  
#define   TASK_SIZE   (test_thread_flag(TIF_ADDR32) ? IA32_PAGE_OFFSET : TASK_SIZE_MAX)
```

- 32 bit 의 경우 [arch/x86/include/asm/page_types.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/page_types.h#L35) 위치에 PAGE_OFFSET 이 __PAGE_OFFSET 으로 정의되어 있으며
```c
#define   PAGE_OFFSET   ((unsigned long)__PAGE_OFFSET)
```
__PAGE_OFFSET 은 [arch/x86/include/asm/page_32_types.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/page_32_types.h#L17) 위치에 아래와 같이 정의되어 있습니다. 
CONFIG_PAGE_OFFSET 은 kernel build time 에 3G 로 정해지며  .config 파일을 통해 조정 할 수 있습니다.
```c
#define   __PAGE_OFFSET_BASE	_AC(CONFIG_PAGE_OFFSET, UL)
#define   __PAGE_OFFSET		__PAGE_OFFSET_BASE
```
- 64 bit 경우 [include/linux/thread_info.h](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/thread_info.h#L74) 에 보시면 current_thread_info 를 통해 가져올 수 있는 [struct thread_info](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/thread_info.h#L55) 의 flags 를 검사하여 [test_ti_thread_flag](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/thread_info.h#L61) 함수를 통해 [TIF_ADDR32](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/thread_info.h#L100) flag 를 검사합니다. TIF_ADDR32 flags 는 x86 specific 한 flag 로 32-bit address space 로 설정되었음을 나타내는 flag 입니다.
```c
#define TASK_SIZE	(test_thread_flag(TIF_ADDR32) ? IA32_PAGE_OFFSET : TASK_SIZE_MAX)
```
설정되어 있다면 [IA32_PAGE_OFFSET](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/processor.h#L846) 이 설정되어 있는지 한번 더 검사 합니다. IA32_PAGE_OFFSET 는 64 bit 에서 32-bit ELF 를 위해 personality system call 로 address space 크기를 조정하는 x86 specific flag 입니다.  설정된 경우 결과적으로 해당 프로세스의 task_strut->task_size 에 초기화될 TASK_SIZE 가 3GB가 됩니다. 
```c
#define IA32_PAGE_OFFSET	((current->personality & ADDR_LIMIT_3GB) ? 0xc0000000 : 0xFFFFe000)
```
TIF_ADDR32 가 설정되어 있지 않다면 [arch/x86/include/asm/processor.h](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/include/asm/processor.h#L841) 에 서 볼 수 있는 것 처럼 guard page 1 개 4KB 만큼을 제외하고 128TB 크기의 address space 를 가지게 됩니다. 
```c
#define TASK_SIZE_MAX	((1UL << 47) - PAGE_SIZE)
```

### 질문 2. IA-32 address space layout 은 ?
p292 에 나와있는 Figure 4-1 을 보시기 바랍니다. 

### 질문 3. Transmeta CPU 가 무었인가?
저소비 전력 CPU 를 생산하는 Transmeta 기업의 CPU 로 Crusoe, Efficeon 의 두개의 x86 호환 CPU Architecture 를 생산한 기업이며, 2007 년 이후 판매를 중단하였다고 합니다. 

## @sungmin1989  질문 사항
### 질문 1. 그림
[study_ppt 참고](https://github.com/DKU-Embedded-Lab/Professional-Linux-Kernel-Architecture/blob/master/study_ppt/Ch04_Vritual_Process_Memory_v1.pdf)

### 질문 2. MMU 가 S/W 가아닌 H/W 로 구성되어야 하는 이유는?
작성중

### 질문 3. 프로그램 실행 시, 반드시 memory 로 올려야 하는 것들은?
load_elf_binary 주석 작성 중...

## @kwanghee0124 질문 사항
### 질문 1. virtual processor address 관리 rbtree 및 update 사항은?
mm 에서의 vm_area_struct 관리에는  red-black tree 가 아니라 augmented-rbtree 가 사용됩니다. 
vm_area_struct 의 관리에 사용되는 augmented rbtree 의 경우 발표때 말씀드린 것 처럼 [vm_area_struct->rb_subtree_gap](http://elixir.free-electrons.com/linux/v4.11/source/include/linux/mm_types.h#L284) 을 augmented value 로 사용하여 [get_unmapped_are](https://elixir.free-electrons.com/linux/v4.11/ident/arch_pick_mmap_layout) 함수에서 architecture 별로 초기화되어 있는 mm->get_unmapped_area 또는 get_unmapped_area_topdown 호출 시 rbtree searching 시에 각 rbnode별 subtree 의 최대 그전 vm_area_struct 와의 거리 정보를 위지하게 함으로써 쉽게 검색이 가능하도록 해줍니다. 이를 위해 augmented rbtree 에 등록하게되는 call back 함수는 아래와 같으며 vma 에 대해 subtree_gap 을 leftchild, rightchild 를 참고하여 update 해 주는 일을 수행합니다. 
```c
static long vma_compute_subtree_gap(struct vm_area_struct *vma)
{
	unsigned long max, subtree_gap;
	max = vma->vm_start;
	if (vma->vm_prev)
		max -= vma->vm_prev->vm_end;
	if (vma->vm_rb.rb_left) {
		subtree_gap = rb_entry(vma->vm_rb.rb_left,
				struct vm_area_struct, vm_rb)->rb_subtree_gap;
		if (subtree_gap > max)
			max = subtree_gap;
	}
	if (vma->vm_rb.rb_right) {
		subtree_gap = rb_entry(vma->vm_rb.rb_right,
				struct vm_area_struct, vm_rb)->rb_subtree_gap;
		if (subtree_gap > max)
			max = subtree_gap;
	}
	return max;
}
```

또한 call back 함수를 등록하는 과정은 아래와 같으며 RB_DECLARE_CALLBACKS 함수를 통해 위의 callback 함수가 사용될 propagate, copy rotate 함수가 선언 및 정의됩니다.
```c
RB_DECLARE_CALLBACKS(static, vma_gap_callbacks, struct vm_area_struct, vm_rb,
		     unsigned long, rb_subtree_gap, vma_compute_subtree_gap)
```

reverse mapping 에서의 vm_area_struct 및 [anon_vma](http://elixir.free-electrons.com/linux/v4.11/source/include/linux/rmap.h#L28) 관리는 [augmented rbtree 기반의 interval tree](http://elixir.free-electrons.com/linux/v4.11/source/include/linux/interval_tree.h) 를 사용합니다.
 [그전 vm_area_struct 에서 shared](http://elixir.free-electrons.com/linux/v2.6.39/source/include/linux/mm_types.h#L158) 를 통해 [raw_prio_tree_node](http://elixir.free-electrons.com/linux/v2.6.39/source/include/linux/prio_tree.h#L14) 로 관리되던 것이 [LWN 문서](https://lwn.net/Articles/514761/)를 참고한 결과 interval tree 로 변경된 것을 확인 할 수 있었습니다. 

### 질문 2. Priority Search Tree(PST) 에서 interval 겹치면 어떻게되나?
PST 는 더이상 커널에 존재하지 않는 자료구조입니다. 

### 질문 3. Anonymous Page 란?
Anonymous page 란 stack 또는 sys_mmap ,sys_brk 등을 통해 heap, mmap 영역에 mapping 된 page 들을 의미하는 것으로 file 에서 읽어온 것이 아니기 때문에 [page->i_mapping](http://elixir.free-electrons.com/linux/v4.11/source/include/linux/mm_types.h#L45) 에 [address_space](http://elixir.free-electrons.com/linux/v4.11/source/include/linux/fs.h#L379) 를 가지는 file-backed page 와는 달리 [anon_vma](http://elixir.free-electrons.com/linux/v4.11/source/include/linux/rmap.h#L28) 에 대한 주소값을 가지고 있습니다. 또한 Kernel 에서는 page->mapping 에 담겨있을 수 있는 address_space 또는 anon_vma 를 쉽게 구분하기 위해 [sizeof(long) 으로 aling 되어 있는](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/fs.h#L397) address_space 를 이용하여 LSB 에 PAGE_MAPPING_ANON 이 설정되어 있다면 anon_vma 로 typecast 할 수 있는 anonymous page 으로 인식하고 설정되어 있지 않다면 file-backed page 로 인식하게 됩니다. rbtree 의 [rb_node->__rb_parent_color](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/rbtree.h#L36) 에서도 이와 같은 trick 을 사용하여 red/black 의 색을 구분하고 있습니다. 

## @bestjae  질문 사항
### 질문 1. mmap2 에서 offset 이  PAGE_SIZE 단위인 것이 왜 file size 가 address_space  보다 커도 mmap 이 가능한것과 무슨관련인가?
mmap2, mmap 소스 주석 중..

### 질문 2. mmap_cache 의 역할은?
기존엔 하나의 vma 를 가진 mmap_cache 만 있었지만 지금은 struct vmcache 로 빠져 4개의 vm_area_struct 를 가지고 있는 구조입니다. vm_area_struct 를 insert, search 등 접근 시, rbtree 를 search 하지 않고, cache 에서 가져갈 수 있도록 해주는 구조이며 sequence number 를 가지고 있어 vm_area_struct  가 속한 mm 을 구분 할 수 있도록 해줍니다. 즉 scheduling 되어 task_struct 가 변경되면 cache 가 비워지고 다시 채워집니다. 

### 질문 3. demand paging?
demand paging 에 대한 설명으로 vm_area_struct 를 통해 생성되거나 vm_end, vm_start 가 증가 하여도 해당 virtual address 에 대한 page table 의 PRESENT_BIT 가 0 이거나 physical address 가 존재하지 않을 수 있고, 실제 접근시 page talbe 이 채워진다는 내용에 대한 것인 것 같습니다. 

## @MyunghoonOh   질문 사항
### 질문 1. legacy layout 에서 stack 과  mmap 이 충돌한다면 어떻게 되는가?
stack size 가 각 process 별 default size 인 8MB 보다 커지게 되는 memory allocation 이 발생시, 그 프로세스는 SIGEGV signal 을 받게되고 segmentation fault 발생하여 종료되며 이를 방지하기 위해 stack 에 접근시 마다 stack pointer 및 stack 크기에 대한 검사가 수행됩니다. kernel 은 프로그램이 수행 중
 vma(mmaped area  등...)의 위치를 변경 할 수 없기 때문에 해당 일의 발생이 예상될 경우, 프로그램 시작 전 ulimit -s 등으로 stack 크기 조정 후 프로그램을 수행해야 합니다. 해당 사항에 대하여 Linux Stack Exchange stack 에 질문을 올린 후 받은 [응답](https://unix.stackexchange.com/questions/407204/program-stack-size)입니다.  크기 임의증가에 따른 mmap 주소 임의 참조에 대한 [LWN article patch](https://lwn.net/Articles/725832/) 를 [첨부](https://lwn.net/Articles/725832/) 하였습니다. 

### 질문 2. sys_remap_file_pages
sys_remap_file_pages 는 현재 지원이 되지 않는 systemcall 이며 ABI 를 위해 남겨 놓았다고 합니다.

### 질문 3. anonymous page 와 file-backed page 의 차이는?
위 질문과 동일
