### ISSUE TITLE
Ch03 Memory Management_p160

### ISSUE THREAD

**Issue by SonJuHyung** [DKU-Embedded-Lab/Professional-Linux-Kernel-Architecture#3]
스터디 자료 : [Professional Linux Kernel Architecture](http://cse.yeditepe.edu.tr/~kserdaroglu/spring2014/cse331/termproject/BOOKS/ProfessionalLinuxKernelArchitecture-WolfgangMauerer.pdf)
  시간 : 11/27 PM 4:00 분
  장소 : 미디어센터 508 호

# 발표팀
## 1. Ch03 스터디 및 커널 분석 자료 작성 
전체 적인 그림 및 구조 설명
일정 
- 11 월 27 일 발표 - 3.3 ( p133 ~ p160 ) 까지

## 2. Ch03 에 나오는 아래 소스 코드들에 대하여 관련 내용 분석 및 주석 작성 commit

# 발표팀 이외 팀
## 1. Ch03 에 대하여 질문
- 11월 25일까지 팀당 질문 총 6개(개인 당 3개)를 만들어 해당 issue 에 comment 작성

## 2. Ch04 11/20 발표팀 질문사항에 대한 설명.

**Comment by SonJuHyung** [comment]
이번 스터디에 p144 에 나와있지만 지금과 구조가 좀 다른  v4.11 에서 각 zone 들의 watermark 가 초기화 되는 [init_per_zone_wmark_min](https://elixir.free-electrons.com/linux/v4.11/source/mm/page_alloc.c#L6924) 과정 부분 설명을 부탁드립니다.  관련 부분에 대하여 자세히 설명해준 [링크](http://jake.dothome.co.kr/zonned-allocator-watermark/)를 발견하여 공부하는 중이지만 많이 이해가 부족한 상태입니다.  
질문 3가지는 해당 부분을 공부하며 따로 올리겠습니다.

**Comment by heyheygo99** [comment]
페이지 범위가 이상해요

**Comment by SonJuHyung** [comment]
@heyheygo99  범위 수정하였습니다.

**Comment by SonJuHyung** [comment]
- [x] 질문 1.
 p135 에서 memory model 들에 대해 hole 이 존재한다는 말이 단순 node 가 여러개라 각
 node 별로 분리가 되어 있어 memory 접근이 연속적이지 않은 것을 의미하는것인가요?
- [x] 질문 2.
p139 에서 node 에 대한 정보를 나타낸 struct pglist_data 의 node_mem_map 필드가  [CONFIG_FLAT_NODE_MEM_MAP](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/mmzone.h#L595) 일 경우 즉 memory model 이 SPARSEMEM 이 아닐 경우에만 struct page 에 대한 배열을 가리키는 것으로 확인하였습니다. NUMA 등의경우엔 그럼 어떻게 page 배열에 접근하나요?
- [x] 질문 3.
P139 의 node 에 대한 정보를 나타낸 struct pglist_data 의 [node_zonelist](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/mmzone.h#L597) 에 대하여  p138 의 설명에 따르면 memory allocation 을 위한 fallback node 들이라고 있는 걸 보았습니다.  [MAX_ZONELIST](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/mmzone.h#L548) 를 보면 FALLBACK 일 경우와 아닌 경우로 나뉘어져 있던데 NOFALLBACK 은 그냥 현재 node 만 가리키는 것이고, FALLBACK 일 경우는 그냥 hop 같은걸로 결정되나요?

**Comment by MyunghoonOh** [comment]
- [x] 질문 1. 
NUMA 시스템에서 각 메모리 노드마다 ZONE들의 타입(ZONE_DMA, ZONE_NORMAL, ZONE_HIGHMEM)이 존재하고있나요? (137 page)


- [ ] 질문 2. 
Critical allocation을 위해서 최소한의 free 메모리 공간을 계산하기 위해서 Zone Watermarks를 계산한다고 하는데, 여기서 Critical allocation은 어떤것들인가요?(144 page)


- [x] 질문 3. 
Hot-N-Cold Pages에서 Cold Page를 식별하는 기준이 무엇인가요?(147 page)

**Comment by kwanghee0124** [comment]
- [x] 질문 1.
p.138 MAX_NR_ZONES 라는 ZONE 영역이 존재하는데 설명은 시스템이 모든 영역을 반복하려할때 end marker로 사용된다 되어 있는데
모든 영역을 반복한다는게 무슨 뜻인가요??

- [x] 질문 2.
p.148 각 cpu마다 page cache를 위해  hot page와 cold page를 관리 하게 되는데
cpu1과 cpu2가 계속 같은 page를 hot page로 가지고 있다면 kernel에서 따로 해주는 작업이 존재하나요?

- [x] 질문 3.
p.154 void *와 unsigned long이 서로 상호 변환 될 수 있다고 나와 있는데 이게 메모리의 할당 size만 나타내게 되는건가요? 아니면 컴파일 최적화가 진행 될 때 void *는 unsigned log 값으로 바뀌어 입력되게 되는건가요?

**Comment by heyheygo99** [comment]
- [ ] 질문 1.
 Essential for memory management are the flags N_HIGH_MEMORY and N_NORMAL_MEMORY. While the first one announces that the zone is equipped with memory that maybe either regular or high memory, N_NORMAL_MEMORY is only set if non-high mem memory is present on a node.(140p)
- 이 부분이 무엇을 얘기하는건지 모르겠습니다. 노드에 존재하지 않는 메모리가 어떤 것이고, 메모리가 높은 메모리는 어떤 것인가요?

- [ ] 질문 2.
 The kernel invokes the ZONE_PADDING macro to generate ‘‘padding‘‘ that is added to the structure to ensure that each lock is in its own cache line. (141p)
- 번역된 내용이, 각각의 잠금 장치가 자체 캐시 라인에 있는지 확인하기 위해 "패딩"을 생성한다고 되어있는데, 이 말이 무슨 말인지 모르겠습니다.

- [ ] 질문 3.
 ZONE_OOM_LOCKED is reserved for an unfortunate situation: If processes use up so much memory that essential operations cannot be completed anymore, then the kernel will try to select the worst memory eater and kill it to obtain more free pages. The flag prevents multiple CPUs from getting into their way in this case.(143p)
- 번역 내용으로, 프로세스가 더 이상 필요하지 않을 경우를 얘기하는데, 프로세스가 더 이상 필요하지 않을 경우는 어떤 경우를 얘기하는 것이고, 커널이 최악의 메모리를 선택한다는 것은 무슨 말인지 모르겠습니다.

**Comment by sungmin1989** [comment]
# 11/27 스터디 질문 답변
-----------------------------
## @SonJuHyung 질문 사항
### 질문 1. 메모리 모델에서의 hole 의 의미
SPARSEMEM 의 경우 [링크참조](http://jake.dothome.co.kr/mm-1/) 에서 언급된 바와 같이 논리적으로 메모리가 연속적으로 보일 수 있어도 실제 실제 물리적으로 연속적이지 않도록 구성될 수가 있다고 합니다. 이때의 이러한  연속적이지 않은 부분을 hole 이라고 합니다. 

### 질문 2. SPARSEMEM 에서의 struct page 관리
node 관련 구조체인 pglist_data 에서 각 page frame 을 관리하는 node_mem_map 필드는 은 아래와 같이 구성되어 있으며 해당 필드를 통해 page 구조체 배열을 가리킵니다. 
```c
typedef struct pglist_data {
   ...
#ifdef CONFIG_FLAT_NODE_MEM_MAP   /* means !SPARSEMEM */
   struct page *node_mem_map;
#endif
   ...
} pg_data_t;
```
 - FLATMEMMEM 의 경우
노드 하나로 구성되어 있으므로 하나의 전역 구조체 [contig_page_data](https://elixir.free-electrons.com/linux/v4.11/source/mm/nobootmem.c#L30) 를 통해 노드를 pglist_data 로 나타내어 node_mem_map 필드로 struct page 의배열을 가리킵니다. 

 - DIDCONTIGMEM 의 경우
노드의 개수만큼 pglist_data  형의 [배열](https://elixir.free-electrons.com/linux/v4.11/source/arch/x86/mm/numa.c#L25)가 생성되어 배열 각 필드의 pglist_data->node_mem_map 필드로 struct page 의 배열을 가리킵니다. 
```c
struct pglist_data *node_data[MAX_NUMNODES] __read_mostly;
EXPORT_SYMBOL(node_data);
```
 - SPARSEMEM 의 경우
section 수 만큼 아래와 같이 struct mem_section 필드의 배열을 가지고 있으며  
[배열](https://elixir.free-electrons.com/linux/v4.11/source/mm/sparse.c#L31)
```c
#ifdef CONFIG_SPARSEMEM_EXTREME
struct mem_section *mem_section[NR_SECTION_ROOTS]
   ____cacheline_internodealigned_in_smp;
#else
struct mem_section mem_section[NR_SECTION_ROOTS][SECTIONS_PER_ROOT]
   ____cacheline_internodealigned_in_smp;
#endif
EXPORT_SYMBOL(mem_section);
```
[mem_section](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/mmzone.h#L1075) 형의 각 배열의 요소는 아래와 같이 section_mem_map 을 통해 struct page 필드를 가리킵니다. 
```c
struct mem_section {
   unsigned long section_mem_map;
   unsigned long *pageblock_flags;
#ifdef CONFIG_PAGE_EXTENSION
   struct page_ext *page_ext;
   unsigned long pad;
#endif
};
```

### 질문 3. FALLBACK 일 경우의 node 순서.
fallback 일 경우 zoneref 의 순서는 latency 가 낮은 즉 hop 이 작은 순서부터로 설정됩니다. 

## @MyunghoonOh 질문사항
### 질문 1. NUMA 에서 노드마다 ZONE들의 타입(ZONE_DMA, ZONE_NORMAL, ZONE_HIGHMEM)이 존재하고있나요? 
관련 [링크](http://jake.dothome.co.kr/build_all_zonelists/) 를 보시면 
ZONE_DMA, ZONE_DMA32, ZONE_NORMAL, ZONE_HIGHMEM, ZONE_MOVABLE 의 총 5개 중 최대 4개까지 조합하여 사용이 가능하며, ZONE_DMA는 기존 ISA버스 기반 디바이스와의 호환성을 위해 존재하고 ZONE_NORMAL은 반드시 존재합니다.( 64비트 4G 미만 RAM 장착을 할 경우, ZONE_DMA32에서 4G까지 처리하므로  ZONE_NORMAL 은 비어있는 공간). ZONE_HIGHMEM은 파편화를 막기위해 ZONE_MOVABLE을 사용하며 64bit system 에서는 사용하지 않습니다.

### 질문 2. Memory Critical Allocation 이란 ?
작성중 ...

### 질문 3. Hot-N-Cold Page 에서 Cold Page 를 식별하는 기준은?
LRU, LFU, second chance등 다양한 정책을 옵션으로 선택하여 이용할 수 있습니다. (메모리에서는 LRU 불가) 현재 리눅스에서는 LRU를 근사한 clock교체 정책으로 hot page를 판단합니다

@kwanghee0124 
### 질문 1. MAX_NR_ZONE 이라는 것이 end marker 로 사용된다는 의미는?
관련 [링크](http://jake.dothome.co.kr/free_area_init_node/) 를 보시면 [free_area_init_nodes()](https://elixir.free-electrons.com/linux/v4.11/source/mm/page_alloc.c#L6475) 와 같은 노드 초기화 함수에서 노드 내부를 순회하기 위한 루프문 내 변수로 사용되는 것을 볼 수 있습니다. 
```c
for (i = 0; i < MAX_NR_ZONES; i++) {
      if (i == ZONE_MOVABLE)
         continue;

      end_pfn = max(max_zone_pfn[i], start_pfn);
      arch_zone_lowest_possible_pfn[i] = start_pfn;
      arch_zone_highest_possible_pfn[i] = end_pfn;

      start_pfn = end_pfn;
   }

```

### 질문 2. cpu1과 cpu2가 계속 같은 page를 hot page로 가지고 있다면 kernel에서 따로 해주는 작업이 존재하나요?
양쪽 캐시에 같은 데이터를 가지고 있어도 별문제가 되지 않을 것 같습니다. 따라서, 커널에서 별다른 작업이 필요하지 않을 것 같습니다.

### 질문 3. void *와 unsigned long 의 서로 상호 변환?
void *가 unsigned long으로 최적화에 의해 치환되는 것은 말이 안되는 것 같습니다. 보편적으로 unsigned long(or long) 자료형은 system에 따라 다른 값을 갖습니다.(32bit = 4byte, 64bit = 8byte) 포인터의 자료형 또한 시스템에 따라 unsigned long과 같은 크기를 같습니다.(32bit = 4byte, 64bit = 8byte) 따라서 본문에서는 형 변환시에 데이터가 손실되지 않는다 라고 이해하시면 될 것 같습니다. 메모리를 관리할 때 포인터 연산을 하는 것이 번거로우므로 리눅스에서는 unsigned long 형식의 변수를 사용합니다.(각 비트를 이용 32개 or 64개)

@heyheygo99 
### 질문 1. 영어 해석
노드에 존재하지 않는 메모리가 아니라 highmem(앞에 읽으세요)이 정의되지 않을 경우가 있는데 N_NORMAL_MEMORY는 이 경우에만 set 된다는 말입니다. 
```c
#ifdef CONFIG_HIGHMEM
   N_HIGH_MEMORY,      /* The node has regular or high memory */
#else
   N_HIGH_MEMORY = N_NORMAL_MEMORY,
#endif
```

### 질문 2. padding 이란?
멀티코어 프로그래밍에서는, 자주 읽히는 데이터가 인접해 있다면, cache line 크기만큼의 간격을 두도록 하는 것이 좋습니다.  패딩(padding)을 이용하여 해당부분을 채운다. 즉, cache line alignment를 위해 padding을 하는 것으로 이해하면 됩니다.

```c
#if defined(CONFIG_SMP)
struct zone_padding {
   char x[0];
} ____cacheline_internodealigned_in_smp;
#define ZONE_PADDING(name)   struct zone_padding name;
#else
#define ZONE_PADDING(name)
#endif
```

### 질문 3. 영어 해석
프로세스가 과다한 메모리를 사용하고 있고  operation이 완료될 수 없는 경우 out of memory를 방지하기 위해 해당 메모리를 회수하여 page를 확보하는 것을 말합니다.
