### ISSUE TITLE
Ch02 Process Management and Scheduling_p105

### ISSUE THREAD

**Issue by SonJuHyung** [DKU-Embedded-Lab/Professional-Linux-Kernel-Architecture#4]
스터디 자료 : [Professional Linux Kernel Architecture](http://cse.yeditepe.edu.tr/~kserdaroglu/spring2014/cse331/termproject/BOOKS/ProfessionalLinuxKernelArchitecture-WolfgangMauerer.pdf)
시간 : 12/11 PM 8:30 분(매주)
장소 : 미디어센터 508 호

# 발표팀
## 1. Ch02 스터디및 발표자료 작성 
전체 적인 그림 및 구조 설명
일정 
- 12 월 11 일 발표 - 2.5 (p64~p105) 까지

## 2. 향후 연구자 및 연구실 커널 분석사항 유지를 위해 Ch02 분석 내용 주석 작성 

# 발표팀 이외 팀
## 1. Ch02 에 대하여 팀당 질문 총 6개(개인당 3개)를 만들어 하루전까지 해당 issue 에 comment 로 제출\
- 12월 9일까지 issue 에 질문 comment  작성
## 2. Ch03 미완성 질문 답변

**Comment by SonJuHyung** [comment]
- [x] 질문 1.
p88 의 policy 부분에 scheduling policy 에 대하여 책의 내용과 달리 현재 v4.11 에서는 아래와
 같이 SCHED_DEADLINE 이 추가되어 있는 것을 확인하였습니다.
   ```c
   /*
    * Scheduling policies
    */
   #define SCHED_NORMAL		0
   #define SCHED_FIFO		1
   #define SCHED_RR		2
   #define SCHED_BATCH		3
   #define SCHED_IDLE		5
   #define SCHED_DEADLINE		6
   ```
   검색해보니 RT Scheduler 보다 우선순위가 놓고, [2014 년 v3.14.2 에 merge]
   (http://retis.sssup.it/~jlelli/talks/rts-like14/SCHED_DEADLINE.pdf) 되었다는 것을 확인하였습니다. 따라서
   본 책에는 deadline scheduler 의 설명이 없을 것 같은데 rt scheduler 보다 우선순위가 높은 deadline 
   scheduler 에 대하여 간단히 설명 부탁드립니다. 

- [x] 질문 2.
p81 의 prepare_binprm 함수에서 책에 나온 부분이 bprm_fill_uid 에 현재 구성되 있는것을 확인하였으며 아래와 같이 SUID, SGID 가 설정안되면 그냥 종료되는 것을 보았습니다.
   ```c
   static void bprm_fill_uid(struct linux_binprm *bprm)
   {
	   struct inode *inode;
	   unsigned int mode;
	   kuid_t uid;
	   kgid_t gid;
           ...
	   inode = bprm->file->f_path.dentry->d_inode;
	   mode = READ_ONCE(inode->i_mode);
	   if (!(mode & (S_ISUID|S_ISGID)))
	   return;
           ...
	   if (mode & S_ISUID) {
	   	   bprm->per_clear |= PER_CLEAR_ON_SETID;
		   bprm->cred->euid = uid;
	   }

	   if ((mode & (S_ISGID | S_IXGRP)) == (S_ISGID | S_IXGRP)) {
		   bprm->per_clear |= PER_CLEAR_ON_SETID;
		   bprm->cred->egid = gid;
	   }
   }
   ```
   혹시 책에서의 SUID, SGID 를확인한다는 말이 실행파일인지검사한다는 말로 이해해도 될지 궁금합니다. 

- [x] 질문 3.
p72 의 copy_process 에서의 process 수 resource limit 확인 과정을 보던 중, 현재 아래와 같이 책과 다르게 [struct cred](http://elixir.free-electrons.com/linux/v4.11/source/include/linux/cred.h#L110) 라는 것이 task_struct 에 있는 것을 확인하였으며 이를 통해 보안 문맥 정보를 나타낸다는 것을 확인하였습니다. 
   ```c
	   if (atomic_read(&p->real_cred->user->processes) >= task_rlimit(p, RLIMIT_NPROC)) {
		   if (p->real_cred->user != INIT_USER &&
		       !capable(CAP_SYS_RESOURCE) && !capable(CAP_SYS_ADMIN))
			   goto bad_fork_free;
	   }
   ```
   task_struct 를 보니 이러한 cred 가 cred, real_cred 등 한 task_struct 당 여러개가 존재하였는데 cred 와 
   real_cred 가 나타내는 것이 어떻게 다른 것일지 궁금합니다. 
   ```c
   struct task_struct {
           ...
           const struct cred __rcu		*real_cred;
           const struct cred __rcu		*cred;
           ...
   }
   ```

질문 2 응답
: SUID는 사용자에게 실행 권한이 아니라 파일 소유자의 권한으로, 프로그램 및 파일을 실행하는 임시 권한을 부여하는 것을 의미합니다. 
관련된 내용으로 여러가지 예를 들면서 설명되어있는 링크를 올려드립니다.
https://www.linuxnix.com/suid-set-suid-linuxunix/

질문 3 응답
: linux에서는 한 task가 다른 task에 접근할 때 작용하는 권한과 다른 task가 이 task에 접근하기 위해 가지고 있어야하는 권한을 분리해 놓았습니다.
따라서 real_cred는 다른 task가 이 task에 접근하기 위해서 가지고 있어야 하는 권한을 의미하며
cred는 이 task가 다른 task에 접근하거나, 특정 작업을 수행할 때 행사하는 권한을 의미합니다.
일시적으로 다른 security context를 가리키도록 override 될 수 있으나 기본적으로는 current->cred == current->cred 라고 합니다.

따라서 권한 상승의 경우 cred로 접근해야 하는게 맞지만, 일반적인 경우 둘은 같은 구조체를 가리키고 있기 때문에 둘 중 어느 쪽으로 접근해서 수정해도 권한 상승이 가능하다고 합니다.

**Comment by sungmin1989** [comment]
- [ ] 질문 1
COW 페이지 상태일때의 메모리 관리 자료구조의 상태(COW 상태임을 표시하는 변수및 flag들)는 어떤가요?

-> 이 부분은 모르겠습니다...

- [ ] 질문 2
namespace는 각각 독립적이어야 좋을 것 같은데 다른 namespace에 프로세스 생성이 가능하도록 설계한 이유가 무엇인가요?

-> 자세하게는 알기 힘들지만,, 상황별로 namespace를 쓰는 이유가 다양합니다.

최근을 예로 들면, Docker나 LXC(Linux Container)가 lightweight한 가상화 플랫폼으로 주목을 받으면서 IPC 통신을 위해 다른 namespace에 프로세스 생성이 가능하도록 설계한 것이 아닐까 생각됩니다. (일반 가상화 시스템보다 적은 자원 소모를 하기 때문에..?) 즉, 개별적인 파일 시스템 공간에서 적은 자원 소모를 통해서 프로세스에 접근하기 위해서..라고 생각됩니다.

- [x] 질문 3
이전에 질문했던 내용인데 context switch 내용이 나와 다시 질문드립니다.
context switch를 할때, CPU register, virtual address 등의 정보를 저장 후 복원 할텐데, x86과 ARM architecture간에 차이는 무엇인가요?

-> 주로 크게 CISC 및 RISC 차이로 나뉠거같은데,
예를 들어 ARM 에서 
![image](https://user-images.githubusercontent.com/20729743/34081481-a295068c-e390-11e7-9cb7-fb571f10fae7.png)
위와 같은 PCB 레이아웃이 있다고 하면, 명령어 구조는
![image](https://user-images.githubusercontent.com/20729743/34081488-b502d56a-e390-11e7-9ba5-da784202c4b7.png)

다음과 같이 나올 것이라고 생각이 됩니다, 
하지만 x86같은 경우는
https://github.com/epicsdeb/cothread/blob/master/context/switch-x86.c
이 주소에 있는 코드처럼 복잡하게 나올 것이라고 생각됩니다.

**Comment by bestjae** [comment]
- [x] Q1,  
- [x] Q2
nice와 load_wetght 사용에 대해 이해가 잘 가지 않습니다.
load_balancing 에서 load_weight를  실제로 어떤식으로 사용하게 되나요? 
우선순위를 위해 nice로 따로 구분지어둔 이유(why 100~140), 처음에 nice값이 결정되는 원리, 미리 가중치가 1.25승으로 계산되어져 있는 이유, 임의적으로 변경하였을때의 영향 이 궁금합니다.
![image](https://user-images.githubusercontent.com/15737269/33819498-20ff1ace-de8e-11e7-8a57-36b245fce0d5.png)

-> prio_to_weight는 nice값에 매칭되는 weight 값을 미리 계산해 둔 테이블로 nice 0 = 1024 기준으로 nice값이 1 차이 날 때 cpu점유율이 10%정도 차이 나도록 계산된 값이라고 합니다.
즉, 어떤 task의 nice 값이 1증가했다면, 이 task의 cpu 점유율이 nice 0 에 머무른 다른 task 보다 약 10% 감소하게 된다고 보시면 됩니다. 여기서 나와있는 계산식으로, (weight ≈ 1024/(1.25^nice))
prio_to_weight[nice] ≈ prio_to_weight[nice+1] * 1.25 에서 1.25는 nice 1의 차이가 cpu 점유율 10% 차이를 만들어 내기 위해서 1.25라는 값을 적용했다고 생각되어집니다. (따라서 임의적으로 변경을 했을 때는, nice가 1 증가함에 따라 cpu 점유율에 대한 값이 달라진다고 생각하면 될 것 같습니다.)
(http://egloos.zum.com/nzcv/v/5795995 자세한 설명 주소)

사용되는 방법으로 idle task를 살펴보게 되면,  load weight가 set_load_weight()를 통해서 p->se.load.weight와 p->se.load.inv_weight에 저장되어서
idle task의 경우에는 load weight가 3으로 predefined 되어 있어서 nice 19에 해당하는 15보다 낮은 값으로 idle task 의 경우 모든 task 보다 낮은 weight를 갖는 방식을 사용하고 있다고 합니다.

- [x] Q3.
새로 생성된 태스크는 캐쉬 친화력의 이유로 부모 태스크가 존재하던 런 큐로 삽입한다고 알고있는데 캐쉬 친화력이 높은 이유와 부모와 다른 런큐에  들어갔을때는 어떻게 되는지 궁금합니다.

-> 다중 CPU 환경이라서 런 큐가 여러개 일 때, 새로 생성되는 테스크가 부모 테스크가 있던 런큐로 삽입됩니다. 자식 테스크가 부모 테스크와 같은 CPU에서 수행될 때 더 높은 캐시 친화력을 얻을 수 있기 때문이라고 합니다.  만약 부모와 다른 런큐로 들어가게되면, 프로세스가 CPU내의 리소스를 놓고 경쟁을 해야하기 때문에 성능적으로 안좋아질 것이라 예상됩니다
