### ISSUE TITLE
Ch04 Virtual Process Memory_p346

### ISSUE THREAD

**Issue by SonJuHyung** [DKU-Embedded-Lab/Professional-Linux-Kernel-Architecture#5]
스터디 자료 : [Professional Linux Kernel Architecture](http://cse.yeditepe.edu.tr/~kserdaroglu/spring2014/cse331/termproject/BOOKS/ProfessionalLinuxKernelArchitecture-WolfgangMauerer.pdf)
시간 : 12/18 PM 2:00
장소 : 미디어센터 508 호

# 발표팀
## 1. Ch04 스터디및 발표자료 작성 
전체 적인 그림 및 구조 설명
일정 
* 12 월 18 일 발표
   *  page fault 과정 상세 (p330 ~ 346) 까지
   *  reverse mapping 보충 및 상세 ( p322 ~ p327 )
      *  interval tree([include/linux/interval_tree_generic.h](http://elixir.free-electrons.com/linux/v4.11/source/include/linux/interval_tree_generic.h#L40))
      *  fork 시 anon_vma 구조 및 형성 과정 ([mm/rmap.c - anon_vma_fork](http://elixir.free-electrons.com/linux/v4.11/source/mm/rmap.c#L313))
      *  reverse mapping 수행 과정([mm/rmap.c - page_referenced](http://elixir.free-electrons.com/linux/v4.11/source/mm/rmap.c#L810))
   *  memory mapping 보충 및 상세 (p314 ~ p318)
      *  memory mapping system call 수행 과정 ( [mm/util.c](http://elixir.free-electrons.com/linux/v4.11/source/mm/util.c#L330) )

## 2. 향후 연구자 및 연구실 커널 분석사항 유지를 위해 Ch04 분석 내용 주석 작성 

# 발표팀 이외 팀
## 1. Ch04 에 대하여 팀당 질문 총 6개(개인당 3개)를 만들어 하루전까지 해당 issue 에 comment 로 제출\
- 12월 17일까지 issue 에 질문 comment  작성
## 2. Ch02 미완성 질문 답변 @heyheygo99

**Comment by sungmin1989** [comment]
- [ ] Q1
페이지를 로드 할 물리 메모리가 충분치 않을 경우, 커널은 시스템을 계속 실행하기 위해 프로세스를 강제 종료하는데, 종료 시킬 프로세스를 선택하는 기준은 무엇이고 이것을 종료시켜도 문제가 없다는 것을 어떻게 보장할까요? 

- [x] Q2
anonymous page들이 뭔지 자세히 설명 부탁드립니다.

- [ ] Q3
주소 공간의 랜덤화(본인 생각에는 아마도 보안을 위해서 일듯)가 커널 2.6.25부터 더욱 증가되었다고 하였는데, 이로 인한 오버헤드는 없는지? 있다면 이걸 어떻게 극복할 수 있을지?


내용이 어려워서 현재 공부중입니다. 질문이 허접하여 죄송합니다.
스터디 이 후에 공부를 더 하여서 얻는 정보가 있으면 공유해 드리겠습니다.

감사합니다.

**Comment by heyheygo99** [comment]
- [ ] Q1.
 the SIGBUS signal is sent to the process.(p336)
어떠한 이유에서든 데이터 접근 실패가 되면 SIGBUS를 전송한다고 합니다. wiki에서는 실제로 주소를 지정할 수 없는 메모리라고 하는데, 책에서 자세히 설명이 나와있지 않아 질문합니다. SIGBUS 신호가 전송되면 어떤 처리를 하는건가요?

- [ ] Q2.
A programming error in the kernel has caused an incorrect address to be accessed — this is a genuine bug. Of course, this should never happen in stable versions but does occur occasionally in developer versions. 
이 부분에선 커널에서의 프로그래밍 에러는 버그 아니면 서드 파티 개발자의 오류라고 짚고 넘어가는데, 만약, 버그라면 이 부분에 대해서는 어떻게 잡아내야 하는건가요? 실제 사례가 있는지 궁금합니다.

- [ ] Q3.
Kernel Page Faults 처리 방식에서 책에서 설명하고 있는 x86이 아닌 ARM에서는 처리하는 방식이 다른가요? 간단하게 차이점이 무엇인지 궁금합니다.

**Comment by kwanghee0124** [comment]
- [ ] Q1.  p338
쓰기 작업을 할 때 shared mapping , private mapping이 있다고 나오는데 page를 참조하는거에 따라서 해당 용어가 사용되는건가요? 읽기 작업을 할때는 상관없는건가요?

- [x] Q2. p339
anonymous page가 백업을 위해서 page를 할당해서 가지고 있는거라고 이해했는데 그럼 anonymous page는 어디에 사용되나요?

- [ ] Q3. p341
exception pixup이 vmalloc이 해결하지 않는 잘못된 주소에 대한 것들을 도중에 복사해서 해결한다고 되어있었는데 잘못된 주소에 대한건 어떤식으로 판별할수 있는건가요?

**Comment by bestjae** [comment]
- [ ] 1. 
Each address space has special address space operations from which the readpage method can be selected.
각 주소공간에 read를 선택할수 잇는 공간이 있다고 하는게 그게 어떤건가요? 아키텍쳐별로 readpage를 연결 시키는 부분인갸요?

- [x] 2.
anonymous_page가 do_anonymous_page()함수를 통해서 사용된다고 하는데 do_anonymous_page가 리눅스 코드에서 handle_pte_fault에서만 쓰이는데 anonymous_page는 페이지가 폴트되어야만 쓰이나요?

- [ ] 3.
get_user 및 put_user 함수는 char, int 등의 ''단순한 '데이터 유형에 대한 포인터를 사용하라고 되어있는데
포인터 연산이 필요해서 단순한 데이터 유형에만 사용할 수 있다고 하는데 정확한 원리가 궁금합니다.
포인터 연산을 동일한 구조체를 선언해서 사용은 안되나요?

**Comment by MyunghoonOh** [comment]
- [ ]  343페이지의 do_page_fault 함수에서 fastcall, __kprobes가 있는데 이들의 기능이 무엇인가요?

- [ ]  __do_fault(페이지 338), do_wp_page(페이지340) 함수에서 lru_cache_add_active과정이 있는데 여기서 Cache는 무엇인가요?

- [ ]  do_page_fault(페이지 331)에서 Save faulting address를 하는 이유가 무엇인가요?

**Comment by SonJuHyung** [comment]
# 12/18 스터디 질문 답변
-----------------------------
## @sungmin1989  질문 사항
### 질문 1. 페이지를 로드 할 물리 메모리가 충분치 않을 경우, 커널은 시스템을 계속 실행하기 위해 프로세스를 강제 종료하는데, 종료 시킬 프로세스를 선택하는 기준은 무엇이고 이것을 종료시켜도 문제가 없다는 것을 어떻게 보장할까요? (추가내용)
작성 해야됨

### 질문 2. anonymous page들이 뭔지 자세히 설명 부탁드립니다.
Anonymous page 란 file-backed page 와 달리, backing store 에서 읽어들이지 않은 sys_brk, sys_mmap 등의 system call 등을 통해 할당한 memory 를 의미합니다. file backed page와 달리 page->mapping 에 address_space structure 가 연결되는 것이 아니라, anon_vma 가 연결되어 reverse mapping 를 수행하기 위한 vma 를 관리하며, file-backed page 가 vma 에 vm_ops 를 가져 filemap_fault 를 통해 data 를 읽어들여 memory 에 올리는 반면 vm_ops 를 가지고 있지 않습니다. 

### 질문 3. 주소 공간의 랜덤화(본인 생각에는 아마도 보안을 위해서 일듯)가 커널 2.6.25부터 더욱 증가되었다고 하였는데, 이로 인한 오버헤드는 없는지? 있다면 이걸 어떻게 극복할 수 있을지? (추가내용)
작성 해야됨

## @heyheygo99 질문 사항
### 질문 1. 데이터 접근 실패가 되면 SIGBUS를 전송한다고 합니다. wiki에서는 실제로 주소를 지정할 수 없는 메모리라고 하는데, 책에서 자세히 설명이 나와있지 않아 질문합니다. SIGBUS 신호가 전송되면 어떤 처리를 하는건가요?(p336)

SIGBUS 란 architecture implement 관련 잘못된 주소에 대한 접근시 발생합니다.  x86 에서 SIGBUS 가 발생하는 몇가지 상황들은 아래와 같습니다.  
 * x86 에서 SIGBUS 가 발생하는 경우.

   - memory fault 에 의해 발생(DRAM 에서의 memory error)

   아래와 같이 page fault 시, __do_page_fault 함수 내에서 물리 page 할당 함수인 handle_mm_fault 의 수행 결과, VM_FAULT_SIGBUS, VM_FAULT_SIGBUS 가 설정되어 있거나, HWPOISON 기능에 의해 memory fault 가 발생한 물리 page 확인 시, do_sigbus 를 호출하여 SIGBUS 가 발생하게 됩니다. 
    ```c
   // linux/x86/mm/fault.c

   static noinline void
   __do_page_fault(struct pt_regs *regs, unsigned long error_code,
		unsigned long address)
   {   
         ...
         fault = handle_mm_fault(vma, address, flags);
         ...
         if (unlikely(fault & VM_FAULT_ERROR)) {
               mm_fault_error(regs, error_code, address, &pkey, fault);
               return;
         }
   }
   ...
   static noinline void
   mm_fault_error(struct pt_regs *regs, unsigned long error_code,
	       unsigned long address, u32 *pkey, unsigned int fault)
   {
         if (fatal_signal_pending(current) && !(error_code & X86_PF_USER)) {
               no_context(regs, error_code, address, 0, 0);
               return;
         }

         if (fault & VM_FAULT_OOM) {
               if (!(error_code & X86_PF_USER)) {
                     no_context(regs, error_code, address, SIGSEGV, SEGV_MAPERR);
                     return;
               }
               pagefault_out_of_memory();
         } else {
               if (fault & (VM_FAULT_SIGBUS | VM_FAULT_HWPOISON | VM_FAULT_HWPOISON_LARGE))
                     do_sigbus(regs, error_code, address, pkey, fault);
               else if (fault & VM_FAULT_SIGSEGV)
                     bad_area_nosemaphore(regs, error_code, address, pkey);
               else
                     BUG();
         }
   }
   ```
   HWPOISON 은 2009 년 patch 된 기능으로 CPU 에서 memory error recovery 를 수행하는 subsystem 입니다. Architecture 의 지원 하에 OS 에서 memory fault/error 가 감지된 page 를 "poisoned" 로 구분하고 해당 page 를 사용하는 process 들을 죽이며, 추후 page 할당 시, 해당 page 의 할당을 방지하는 recovery subsystem 입니다. (MCA(Machine Check Architecture) recovery subsystem). memory error 는 cosmic rays 등에 의해 DRAM/SRAM 의 bit 가 변경되는 일시적인(리셋하거나 데이터를 새로 작성 시, 정상 작동) soft error 와  영구적인(reset 으로도 같은 에러 검ㅅ출) hard error 로 구분됩니다. 이러한 error 들에 대하여 hardware 에 의해 detect 된 후, 64-bit data word 내에 single bit error 가 발생한 경우는 ECC(Error Correcting Codes) 에 의해 수정이 가능하지만 64-bit data word 내에 multi bit error 가 발생한 경우엔 kernel panic 이 발생하여 죽게되는 기존 kernel 의 memory fault handling mechanism 을 실제 memory fault 난 곳이 실행중인 process 에 영향을 미치지 않는 경우 무시하도록 하여 memory fault handling 을 delaying 하는 mechanism 입니다. CONFIG_MEMORY_FAILURE 를 통해 설정이 가능합니다.

   ```c
   // linux/arch/x86/mm/fault.c
   static void do_sigbus(struct pt_regs *regs, unsigned long error_code, unsigned long address,
         struct vm_area_struct *vma, unsigned int fault)
   {
         struct task_struct *tsk = current;
         int code = BUS_ADRERR;

         /* Kernel mode? Handle exceptions or die: */
         if (!(error_code & PF_USER)) {
               no_context(regs, error_code, address, SIGBUS, BUS_ADRERR);
               return;
         }

         /* User-space => ok to do another page fault: */
         if (is_prefetch(regs, error_code, address))
               return;

         tsk->thread.cr2		= address;
         tsk->thread.error_code	= error_code;
         tsk->thread.trap_nr	= X86_TRAP_PF;

   #ifdef CONFIG_MEMORY_FAILURE
         if (fault & (VM_FAULT_HWPOISON|VM_FAULT_HWPOISON_LARGE)) {
               printk(KERN_ERR "MCE: Killing %s:%d due to hardware memory corruption fault at %lx\n",
                     tsk->comm, tsk->pid, address);
               code = BUS_MCEERR_AR;
         }
   #endif
         force_sig_info_fault(SIGBUS, code, address, tsk, vma, fault);
   }
   ```
   do_sigbus 함수에서는 kernel mode 일 경우, address 에 대한 exception 이 등록되었는지 확인 후, 등록이 
되어 있지 않다면 Oops 가 수행되며 user mode 일 경우, 현재 task 에 SIGBUS 가 전송됩니다. 

   - interrupt/exception 로 인하여 발생

   segment not present, stack segment, fault, alignment check 에 해당하는 interrupt/exception 발생 시, SIGBUS 가 발생할 수 있습니다.  page fault 의 handler 함수가 do_page_fault 함수를 통해 수행된 것과 같이 X86_TRAP_NR, X86_TRAP_SS, X86_TRAP_AC 에 해당하는 interrupt/trap gate 들은  아래와 같이 trap_init 함수에서 set_intr_gate 함수를 통해 vector number 와 global symbol name 을 인자로 받아 등록이 됩니다.  
   ```c
   // linux/arch/x86/kernel/traps.c

   void __init trap_init(void)
   {
      ...
      set_intr_gate(X86_TRAP_SS, stack_segment);
      set_intr_gate(X86_TRAP_NP, segment_not_present);
      set_intr_gate(X86_TRAP_AC, alignment_check);
      ...
      cpu_init();
      x86_init.irqs.trap_init();
      ...
   }
   ```
   등록되는 각각의 gate 들은 아래와 같이 미리 정의된 interrupt/exception vector 번호에 해당하는 gate 들이라고 할 수 있습니다. 
   ```c
   // linux/arch/x86/include/asm/traps.h

   enum {
         X86_TRAP_DE = 0,	/*  0, Divide-by-zero */
         X86_TRAP_DB,		/*  1, Debug */
         X86_TRAP_NMI,		/*  2, Non-maskable Interrupt */
         X86_TRAP_BP,		/*  3, Breakpoint */
         X86_TRAP_OF,		/*  4, Overflow */
         X86_TRAP_BR,		/*  5, Bound Range Exceeded */
         X86_TRAP_UD,		/*  6, Invalid Opcode */
         X86_TRAP_NM,		/*  7, Device Not Available */
         X86_TRAP_DF,		/*  8, Double Fault */
         X86_TRAP_OLD_MF,	/*  9, Coprocessor Segment Overrun */
         X86_TRAP_TS,		/* 10, Invalid TSS */
         X86_TRAP_NP,		/* 11, Segment Not Present */
         X86_TRAP_SS,		/* 12, Stack Segment Fault */
         X86_TRAP_GP,		/* 13, General Protection Fault */
         X86_TRAP_PF,		/* 14, Page Fault */
         X86_TRAP_SPURIOUS,	/* 15, Spurious Interrupt */
         X86_TRAP_MF,		/* 16, x87 Floating-Point Exception */
         X86_TRAP_AC,		/* 17, Alignment Check */
         X86_TRAP_MC,		/* 18, Machine Check */
         X86_TRAP_XF,		/* 19, SIMD Floating-Point Exception */
         X86_TRAP_IRET = 32,	/* 32, IRET Exception */
   };
   ```
   또한 위의 각 interrupt/exception vector 의 gate 들에 대해 수행되어야 할 함수들이 아래와 같이 idtentry 매크로를 통해 각 gate 의 global symbol name, exception handler, err code 포함 여부 등의 정보로 정의가 되어 있습니다(paranoid, shift_ist 생략). 
   ```c
   // linux//arch/x86/entry/entry_64.S

   idtentry stack_segment		do_stack_segment	has_error_code=1
   idtentry segment_not_present		do_segment_not_present		has_error_code=1
   idtentry alignment_check		do_alignment_check		has_error_code=1
   trace_idtentry page_fault	do_page_fault		has_error_code=1
   ```

   위의 do_stack_segment, do_segment_not_present, do_alignment_check 함수들은 아래의 DO_ERROR 매크로에 의해 각각 의 global symbol name 에 맞는 함수들이 생성되게 됩니다. (segment_not_present 의 경우, do_segment_not_present 함수가 생성되어 de_error_trap 호출)
   ```c
   // linux/arch/x86/kernel/traps.c

   #define DO_ERROR(trapnr, signr, str, name)				\
   dotraplinkage void do_##name(struct pt_regs *regs, long error_code)	\
   {									\
         do_error_trap(regs, error_code, str, trapnr, signr);		\
   }
   ...
   DO_ERROR(X86_TRAP_NP,     SIGBUS,  "segment not present",	segment_not_present)
   DO_ERROR(X86_TRAP_SS,     SIGBUS,  "stack segment",		stack_segment)
   DO_ERROR(X86_TRAP_AC,     SIGBUS,  "alignment check",		alignment_check)
   ```
   결과적으로 호출되는 아래와 같은 do_error_trap 함수에서는 notify_die 를 통해 kernel panic, kernel oops, nmi interrupt 등의 발생가능한 event 의 발생을 알리도록 notifier chain 에 등록하고 do_trap 함수를 호출하게 됩니다. do_trap 함수에서는 먼저 do_trap_no_signal 함수를 통해 kernel mode 에서 발생한 exception 일 경우, fixup_exception 함수를 수행하여 exception 이 발생한 address 즉 (regs->ip) 가 exception table 에 등록되었는지 검사하여 handler 를 호출합니다. 등록되어 있지 않다면 die 함수를 통해 stack 정보등을 출력하고 Oops 가 발생합니다.  user mode 에서 발생한 exception 일 경우, do_tarp_no_signal 함수를 바로 빠져나오고, force_sig_info 함수를 통해 현재 task 에게 SIGBUS signal 을 전송합니다.
   ```c
   // linux/arch/x86/kernel/traps.c

   static void do_error_trap(struct pt_regs *regs, long error_code, char *str, unsigned long trapnr, int signr)
   {
         siginfo_t info;

         RCU_LOCKDEP_WARN(!rcu_is_watching(), "entry code didn't wake RCU");

         if (notify_die(DIE_TRAP, str, regs, error_code, trapnr, signr) != NOTIFY_STOP) {
               cond_local_irq_enable(regs);
               do_trap(trapnr, signr, str, regs, error_code, fill_trap_info(regs, signr, trapnr, &info));
         }
   }
   ... 
   static void do_trap(int trapnr, int signr, char *str, struct pt_regs *regs, long error_code, siginfo_t *info)
   {
         struct task_struct *tsk = current;

         if (!do_trap_no_signal(tsk, trapnr, str, regs, error_code))
               return;

         tsk->thread.error_code = error_code;
         tsk->thread.trap_nr = trapnr;

         if (show_unhandled_signals && unhandled_signal(tsk, signr) && printk_ratelimit()) {
               pr_info("%s[%d] trap %s ip:%lx sp:%lx error:%lx", tsk->comm, tsk->pid, str,
                        regs->ip, regs->sp, error_code);
               print_vma_addr(KERN_CONT " in ", regs->ip);
               pr_cont("\n");
         }

         force_sig_info(signr, info ?: SEND_SIG_PRIV, tsk);
   }
   ...
   ```
   ```c
   // linux/arch/x86/mm/extable.c
   
   int fixup_exception(struct pt_regs *regs, int trapnr)
   {
         const struct exception_table_entry *e;
         ex_handler_t handler;

         e = search_exception_tables(regs->ip);
         if (!e)
            return 0;

         handler = ex_fixup_handler(e);
         return handler(e, regs, trapnr);
   }
   ```
   
### 질문 2. 커널에서의 프로그래밍 에러는 버그 아니면 서드 파티 개발자의 오류라고 짚고 넘어가는데, 만약, 버그라면 이 부분에 대해서는 어떻게 잡아내야 하는건가요? 실제 사례가 있는지 궁금합니다.(p341)

작성 해야됨

### 질문 3. Kernel Page Faults 처리 방식에서 책에서 설명하고 있는 x86이 아닌 ARM에서는 처리하는 방식이 다른가요? 간단하게 차이점이 무엇인지 궁금합니다.(추가내용)

작성 해야됨

## @kwanghee0124 질문 사항
### 질문 1. 쓰기 작업을 할 때 shared mapping , private mapping 을 구분할 필요가 있다고 나오는데 page를 참조하는거에 따라서 해당 용어가 사용되는 것인가요? 읽기 작업을 할때는 상관없는건가요?

   private mapping 과 shared mapping 의 차이는 기본적으로 mapping 내용을 다른 process 와의 공유 여부에 있으며, file-backed page 인 경우 추가적으로 다른점이 존재합니다. 먼저 page fault 과정에서의 아래와 같은 handle_pte_fault 함수 수행시 anonymous page 와 file-backed page 에 대하여 다르게 수행을 하게 됩니다. anonymous page 의 경우 vm_area_struct 에 vm_ops 를 가지고 있지 않기 때문에  do_anonymous_page 함수를 수행하게 되며 file-backed page 의경우 do_fault 함수를 수행하게 됩니다.

   ```c
   // linux/mm/memory.c

   static int handle_pte_fault(struct vm_fault *vmf)
   {
         ...
         if (!vmf->pte) {
               if (vma_is_anonymous(vmf->vma))
                        return do_anonymous_page(vmf);
               else
                        return do_fault(vmf);
         }
         ...         
   }
   ``` 
   file-backed page 를 처리하는 do_fault 함수의 수행에서는 다시 현재 접근이 read 인지 write 인지를 구분하고 write 인 경우, private mapping 경우와 shared mapping 인 경우를 구분하여 수행하게 됩니다. private mapping 인 경우, do_cow_fault 함수가 수행되며, shared mapping 인 경우에는 do_shared_fault 함수가 수행됩니다. 
   ```c
   // linux/mm/memory.c

   static int do_fault(struct vm_fault *vmf)
   {
         struct vm_area_struct *vma = vmf->vma;
         int ret;

         if (!vma->vm_ops->fault)
               ret = VM_FAULT_SIGBUS;
         else if (!(vmf->flags & FAULT_FLAG_WRITE))
               ret = do_read_fault(vmf);
         else if (!(vma->vm_flags & VM_SHARED))
               ret = do_cow_fault(vmf);
         else
               ret = do_shared_fault(vmf);
         ...
   }
   ```
   file-backed page 의 private mapping 의 경우, 아래와 같이 anon_vma_prepare 를 통해 새로 생성될 anonymous page 의 reverse mapping 을 위한 anon_vma, anon_vma_chain 구성 및 alloc_page_vma 를 통해 anonymous page 할당 후,  __do_fault 함수와  copy_user_highpage 함수를 통해 연결된 file system 의 fault 함수로 읽어온(ext4 의 경우 ext4_filemap_fault -> filemap_fault ) page cache 의 내용을 새로 생성한 anonymous page 에 복사함으로써 page 의 내용이 backing store 와는 독립적으로 동작도록 합니다. 따라서 private mapping 이며, file-backed page 인 경우에는 page 내에서 변경한 내용이 storage 내의 file 에는 반영이 되지 않습니다. 
   ```c
   // linux/mm/memory.c

   static int do_cow_fault(struct vm_fault *vmf)
   {
         if (unlikely(anon_vma_prepare(vma)))
                  return VM_FAULT_OOM;

         vmf->cow_page = alloc_page_vma(GFP_HIGHUSER_MOVABLE, vma, vmf->address);
         if (!vmf->cow_page)
                  return VM_FAULT_OOM;

         if (mem_cgroup_try_charge(vmf->cow_page, vma->vm_mm, GFP_KERNEL, &vmf->memcg, false)) {
                  put_page(vmf->cow_page);
                  return VM_FAULT_OOM;
         }

         ret = __do_fault(vmf);
         if (unlikely(ret & (VM_FAULT_ERROR | VM_FAULT_NOPAGE | VM_FAULT_RETRY)))
                  goto uncharge_out;
         if (ret & VM_FAULT_DONE_COW)
                  return ret;

         copy_user_highpage(vmf->cow_page, vmf->page, vmf->address, vma);
         __SetPageUptodate(vmf->cow_page);

         ret |= finish_fault(vmf);
         ...
   }
   ```
   file-backed page 의 shared mapping 의 경우, 별도의 anonymous page 를 생성하여 복사하는 과정 없이 __do_fault 함수를 통해 읽어들이는 것으로 함수 수행을 마치게 됩니다. 이를 통해 해당 page 는 page 의 mapping 에 address_space struct 를 가진  file-backed page 이므로 page 내의 변경사항이 storage 의 file 내에 반영이 되며(unmap 또는 msync), 여러 프로세스간의공유도 가능하게 됩니다. 
   ```c
   // linux/mm/memory.c

   static int do_shared_fault(struct vm_fault *vmf)
   {
         ...
         ret = __do_fault(vmf);
         if (unlikely(ret & (VM_FAULT_ERROR | VM_FAULT_NOPAGE | VM_FAULT_RETRY)))
		return ret;

         if (vma->vm_ops->page_mkwrite) {
                  unlock_page(vmf->page);
                  tmp = do_page_mkwrite(vmf);
                  if (unlikely(!tmp || (tmp & (VM_FAULT_ERROR | VM_FAULT_NOPAGE)))) {
                           put_page(vmf->page);
                           return tmp;
                  }
         }

         ret |= finish_fault(vmf);
         if (unlikely(ret & (VM_FAULT_ERROR | VM_FAULT_NOPAGE | VM_FAULT_RETRY))) {
                  unlock_page(vmf->page);
                  put_page(vmf->page);
                  return ret;
         }

         fault_dirty_shared_page(vma, vmf->page);
         return ret;
   }
```
   read 의 경우엔 write 연산과 달리, private & shared 를 구분할 필요가 없이 같은 page 를 읽어도 되므로, vm->flags 에 대한 write 여부 검사등을 수행하지 않고 진행이 되는 것을 아래와 같이 확인 할 수 있습니다. do_fault_around 함수를 통해 (ext4 의  경우map_pages->filemap_map_pages) 미리 주변 page 를 불러오고 __do_fault 로 읽어들이는 것을 볼 수 있습니다. 
```c
   // linux/mm/memory.c

   static int do_read_fault(struct vm_fault *vmf)
   {
         struct vm_area_struct *vma = vmf->vma;
         int ret = 0;

         if (vma->vm_ops->map_pages && fault_around_bytes >> PAGE_SHIFT > 1) {
                  ret = do_fault_around(vmf);
                  if (ret)
                     return ret;
         }

         ret = __do_fault(vmf);
         if (unlikely(ret & (VM_FAULT_ERROR | VM_FAULT_NOPAGE | VM_FAULT_RETRY)))
                  return ret;

         ret |= finish_fault(vmf);
         ...
   }
```

### 질문 2. Anonymous page 란?
동일질문이므로 생략합니다. 

### 질문 3. exception_fixup이 vmalloc이 해결하지 않는 잘못된 주소에 대한 것들을 도중에 복사해서 해결한다고 되어있었는데 잘못된 주소에 대한건 어떤식으로 판별할수 있는건가요?
작성 해야됨

## @bestjae  질문 사항
### 질문 1. 각 주소공간에 read를 선택할수 잇는 공간이 있다고 하는게 그게 어떤건가요? 아키텍쳐별로 readpage 를 연결 시키는 부분인갸요?(p338)
작성 해야됨

### 질문 2. 요청 필요
작성 해야됨

### 질문 3. get_user 및 put_user 함수는 char, int 등의 ''단순한 '데이터 유형에 대한 포인터를 사용하라고 되어있는데 포인터 연산이 필요해서 단순한 데터 유형에만 사용할 수 있다고 하는데 정확한 원리가 궁금합니다. 포인터 연산을 동일한 구조체를 선언해서 사용은 안되나요?(p344)
작성 해야됨

## @MyunghoonOh   질문 사항
### 질문 1. do_page_fault 함수에서 fastcall, __kprobes가 있는데 이들의 기능이 무엇인가요? (p343)
작성 해야됨

### 질문 2. __do_fault(페이지 338), do_wp_page(페이지340) 함수에서 lru_cache_add_active과정이 있는데 여기서 Cache는 무엇인가요?
작성 해야됨

### 질문 3. do_page_fault(페이지 331)에서 Save faulting address를 하는 이유가 무엇인가요?
작성 해야됨
