### ISSUE TITLE
Ch03 Memory Management_p199

### ISSUE THREAD

**Issue by SonJuHyung** [DKU-Embedded-Lab/Professional-Linux-Kernel-Architecture#7]
스터디 자료 : [Professional Linux Kernel Architecture](http://cse.yeditepe.edu.tr/~kserdaroglu/spring2014/cse331/termproject/BOOKS/ProfessionalLinuxKernelArchitecture-WolfgangMauerer.pdf)
시간 : 12/27 ( PM 2:00~PM 4:00 )
장소 : 미디어센터 508 호

# 발표자
## 1. 스터디 발표자료 작성 
 - Ch03(~p199) 전체 적인 그림 및 구조 설명, 소스 분석사항 설명
## 2. 소스 분석사항 기록 
 - 향후 연구자 및 연구실 커널 분석사항 유지를 위해 Ch03 분석 내용 주석 작성 

# 발표자 이외 인원
## 1. 현재 스터디 질문 제출
 - Ch03 에 대하여 12월 17일까지 개인당 질문 5개 를 만들어 하루전까지 해당 issue 에 comment 로 제출
## 2. 지난 스터디 질문 답변
 - Ch04 미완성 질문 답변 및 설명

**Comment by SonJuHyung** [comment]
- [ ] 질문  1 . 
p167 의 zone 의 fallback list 생성 과정이 현재와 조금 다르게 구성되어 있는 것을 확인하였으며 현재는 [zonelist](https://elixir.free-electrons.com/linux/v4.11/source/include/linux/mmzone.h#L574) 의 zoneref 라는 이름으로 되어 있는것을 확인하였습니다. 
     ```c
     struct zoneref {
	     struct zone *zone;	/* Pointer to actual zone */
	     int zone_idx;		/* zone_idx(zoneref->zone) */
     };

     struct zonelist {
	     struct zoneref _zonerefs[MAX_ZONES_PER_ZONELIST + 1];
     };
     ```
     소스코드를 보던 중 현재 구조에서 ZONELIST_FALLBACK 에 해당하는 fallback 순서가 32-bit 일 경우에     는 zone 단위로fallback 을 구성하고, 64bit 일 경우에는 node 단위로 구성하는 것을 확인하였습니다. 32-bit, 64-bit 일 경우 이렇게 나뉘는 이유가 HIGHMEM 의 유무와 관련이 있는 건가요? 이유가 궁금합니다. 

 - [ ] 질문 2. 
node 를 나타내는 pglist_data 의 fallback list 가 NUMA 의 경우, ZONELIST_NOFALLBACK 이 추가적으로 있는 것을 보았습니다. 이를 현재 node 의 할당할경우의 fallback 순서로 이해해도 될까요?
     ```c
     typedef struct pglist_data {
	     struct zone node_zones[MAX_NR_ZONES];
	     struct zonelist node_zonelists[MAX_ZONELISTS];
             ...
     }
     enum {
	     ZONELIST_FALLBACK,	/* zonelist with fallback */
     #ifdef CONFIG_NUMA
	     ZONELIST_NOFALLBACK,	/* zonelist without fallback (__GFP_THISNODE) */
     #endif
	     MAX_ZONELISTS
     };

     ```

- [ ] 질문 3.
     p175 의 1G/3G 로의 virtual address space 를 나눈 이유를 설명하는 부분 중 두번째에 아래와 같이 설명되어 있는 부분을 보았습니다. 

     ![image](https://user-images.githubusercontent.com/11549851/34303943-fd6a1014-e77a-11e7-8034-0c51d050ad5d.png)

     글에 따르면 page table operation 이 따로 없이 direct mapping 영역을 접근하기 위해 구분을 한다고 하여 direct mapping area 인 896MB 영역 의 경우, virtual address 로 __pa 등의 함수를 통해 단순 PAGE_OFFSET 을 빼는 작업만으로 physical address 등을 알 수 있으므로 swapper_pg_dir 에 따로 기록될 필요가 없고, vmalloc area, kmap, fixed mapping area 에 해당하는 128 MB 크기의 영역에 해당하는 부분만 swapper_pg_dir 에 mapping 된다고 이해하였으나 해당 부분을 질문해본 결과  전체 1G 영역에 대하여 mapping 이 이루어 진다고 답변을 받았습니다. 혹시 그렇다면 page attribute bit 등의 정보를 위해 mapping 정보는 가지고 있되 물리 memory 에 접근 할 때에는 __pa 를 통해 접근하는 것일지 궁금합니다. 

- [ ] 질문 4. 
p192 의 bootmem_data 구조를 읽던 도중 검색 결과 다음과 같은 [patch](https://lwn.net/Articles/576281/) 를 발견하였고, bootmem_data 는 여러 architecture 에서 거의 사용하지 않으며 다음 [블로그 의 글](http://jake.dothome.co.kr/bootmem/) 을 통해 memblock 으로 대체된 것을 확인하였습니다. 또한 제 서버에서도 default 로 CONFIG_NO_BOOTMEM 이 설정되어 있는 것을 확인하였습니다. 
     ![image](https://user-images.githubusercontent.com/11549851/34304419-06cbc326-e77d-11e7-866e-97892cf7061b.png)
     대체된 memblock 에 대한 설명을 부탁드립니다. 

- [ ] 질문 5.
추가적으로 소스분석을 하여 올리겠습니다.

**Comment by MyunghoonOh** [comment]
- [ ] 182 page 마지막 부분에서 커널의 페이지는 _PAGE_GLOBAL 속성이 설정된다고 언급되어있습니다. 이 커널 페이지들은 context switch 과정에서 TLB flush 되지않고, __flush_all_tlb 함수를 통해 TLB flush 된다고합니다. 이 부분에서 저는 _PAGE_GLOBAL 속성이 설정된 페이지들만 TLB flush하는 기능이 필요없는지가궁금합니다.

- [ ]  187 page의 Registering Region on AMD64 부분에서 e820을 통해 active memory region을 찾는데, 여기서 active/inactive memory가 무엇을 뜻하는지 궁금합니다.
