### ISSUE TITLE
Ch02 Process Management and Scheduling_p132, Ch06 Device Drivers_p406

### ISSUE THREAD

**Issue by SonJuHyung** [DKU-Embedded-Lab/Professional-Linux-Kernel-Architecture#9]
스터디 자료 : [Professional Linux Kernel Architecture](http://cse.yeditepe.edu.tr/~kserdaroglu/spring2014/cse331/termproject/BOOKS/ProfessionalLinuxKernelArchitecture-WolfgangMauerer.pdf)
시간 : 1/10 PM 2:00 분(매주)
장소 : 미디어센터 508 호

# 발표자
## 1. Ch02, Ch06 스터디및 발표자료 작성 
전체 적인 그림 및 구조 설명
일정 
- 1 월 10 일 발표 - 2.5 (p106 ~ p132,  p391 ~ 406) 까지

## 2. 향후 연구자 및 연구실 커널 분석사항 유지를 위해 Ch02, Ch06 분석 내용 주석 작성 

# 발표자 이외 인원
## 1. Ch02 에 대하여 팀당 질문 인당 3개를 만들어 하루전까지 해당 issue 에 comment 로 제출
- 1월 9일까지 issue 에 질문 comment  작성

**Comment by SonJuHyung** [comment]
- [ ] 질문 1. 
p108 의 [update_curr](http://elixir.free-electrons.com/linux/v4.11/source/kernel/sched/fair.c#L844) 함수내에서 [sched_prio_to_weight](http://elixir.free-electrons.com/linux/v4.11/source/kernel/sched/core.c#L7288) 을 기반으로 vruntime 을 계산하는 함수인 __calc_delta 함수에서 64 bit 의 경우, 기존 weight 값이 아닌 [load down](http://elixir.free-electrons.com/linux/v4.11/source/kernel/sched/sched.h#L87) 을 수행해 주는 이유가 무었인가요?  64 bit 에선 vruntime 계산시 그럼 기존 nice 에 해당하는 weight 보다 더 낮은  weight 값으로 vruntime 을 계산하는 건지 궁금합니다. 또한 이러한 vtime update 는 scheduler tick  시, 선점시 호출이 된다고 생각해도 될지 궁금합니다. 

- [ ] 질문 2.
p126 에서 group scheduling 이라는 것의 개념에 대한 이해가 질문을 드리게 되었습니다. 이번에
 스터디자료를 보며 task_struct 내의 se 를 통해 같은 scheduling entity 에 속한 task_struct 값들을 run queue 에 enqueue/dequeue 하는 과정들을 확인하였으며, group scheduling 이 p126 의 그림을
 통해 scheduling entity 에따라 scheduling 되고, 그 scheduling entity 에 따라 할당받은 time slice 를 같은 entity 내부에서 fair 하게 가져간다고 이해하였습니다. 그러면 같은 sched_entity 에 속하는 task  들은 자신의 weight 이나 priority 가 아닌 sched entity 의 root 에 해당하는 task struct 의 vruntime 에 따라 결국 time slice 를 받게 되는것으로 이해해도될지 궁금합니다. 

- [ ] 질문 3.
추가질문을 작성하겠습니다.

**Comment by bestjae** [comment]
- [ ] Q1.
TASK_KILLABLE, killable_sleep이 쓰이는 이유를 잘 모르겠습니다. 현재 커널에서도 쓰이고 있나요?
https://lwn.net/Articles/288056/

- [ ] Q2.
디바이스 드라이버에서 메이저 번호와 마이너 번호를 구분 하는 이유와 32비트에서 12 / 20 으로 비대칭 분할할때 생기는 문제가 무엇인가요?

- [ ] Q3.
/dev/ttyXX등에서 사용하는 직렬 인터페이스가 어떤 것 인가요? 따로 나뉘어 관리하는 이유가 무엇인가요
